### PR TITLE
Rename layers and classes as discussed.

### PR DESCRIPTION
**Pull request by emacgillavry**
Changes have been discussed w/ @lpsmitamsterdam Data Amsterdam and will be catered for in `assets/map-collections.config.json` and `assets/map-legends.config.json` in [MapLayers](https://github.com/Amsterdam/maplayers) project.

### CODE REVIEW

**Review by Doldenburgamsterdam — DISMISSED** [review]
Check

**Review by Doldenburgamsterdam — DISMISSED** [review]
Dit is dezelfde toch?

**Review by Doldenburgamsterdam — DISMISSED** [review]
Check

**Review by Aziza-Adam — DISMISSED** [review]

**Review by Aziza-Adam — APPROVED** [review]

**Review by barrydaniels-nl — DISMISSED** [review]
Ok

**Review by Doldenburgamsterdam — APPROVED** [review]

**Review by Doldenburgamsterdam — DISMISSED** [review]
check

**Review by Aziza-Adam — APPROVED** [review]

**Pull request closed without merging**
